### ISSUE TITLE
[SOLVED] PacketWriter: Written PCAP smaller than input file

### ISSUE THREAD

**Issue by patrickj0607** [mfontanini/libtins#161]
Hello,
I am using the PacketWriter to write multiple PCAPs into one PCAP file. As a first step I tried to write all packets of a single input file to the output file. I noticed that PacketWriter is not writing all packets 1 by 1 to the pcap. The packet number keeps the same, but the total file size is different:

Input file:
Size: 3 371 692 bytes
Packets: 24793

Output file:
Size: 2 415 335 bytes
Packets: 24793

The implemented code consists simply of these lines:

```
std::string PcapProcessor::mergePcaps(const std::string pcap_path) {
    std::string new_filepath = file_path;

    FileSniffer sniffer_base(file_path);
    sniffer_base.set_extract_raw_pdus(false);   // NOTE: I also tried 'true' here - no change
    SnifferIterator iterator_base = sniffer_base.begin();

    PacketWriter writer(new_filepath, PacketWriter::ETH2);

    // Go through base PCAP and merge packets by timestamp
    while (iterator_base != sniffer_base.end()) {
            writer.write(*iterator_base);
            iterator_base++;
    }
    return new_filepath;
}
```

What could be the reason for this strange behavior?

Thank you for your support!

**Comment by mfontanini** [comment]
Can you provide a sample of that pcap file? I don't need the entire pcap file, just a sample with a few packets so I can reproduce the issue.

Thanks!

**Comment by einarjon** [comment]
Hi

Isn't this simply that the written packets don't write all the fields? -
some PDUs might be limited.
Compare the 2 pcap files in wireshark and see what is missing. Maybe using
smaller files would be easier.

Regards
Einar Jón

Hello,
I am using the PacketWriter to write multiple PCAPs into one PCAP file. As
a first step I tried to write all packets of a single input file to the
output file. I noticed that PacketWriter is not writing all packets 1 by 1
to the pcap. The packet number keeps the same, but the total file size is
different:

Input file:
Size: 3 371 692 bytes
Packets: 24793

Output file:
Size: 2 415 335 bytes
Packets: 24793

The implemented code consists simply of these lines:

std::string PcapProcessor::mergePcaps(const std::string pcap_path) {
    std::string new_filepath = file_path;

    FileSniffer sniffer_base(file_path);
    sniffer_base.set_extract_raw_pdus(false);   // NOTE: I also tried
'true' here - no change
    SnifferIterator iterator_base = sniffer_base.begin();

    PacketWriter writer(new_filepath, PacketWriter::ETH2);

    // Go through base PCAP and merge packets by timestamp
    while (iterator_base != sniffer_base.end()) {
            writer.write(*iterator_base);
            iterator_base++;
    }
    return new_filepath;
}

What could be the reason for this strange behavior?

Thank you for your support!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mfontanini/libtins/issues/161>, or mute the thread

**Comment by mfontanini** [comment]
Yeah that's very likely what's happening, but I'd still like to know which PDUs are doing that, because they shouldn't be doing it.

**Comment by patrickj0607** [comment]
Hello, I already tried to compare the PCAP files in Wireshark. For testing purposes I only work with relatively small files (up to 95 megabytes, ~ 1.5M packets) which are already difficult to compare. Later the application should also process large files (> 10 GBytes). 

As the PCAP file examples are too big, I uploaded them in my dropbox, see [1]. There you can find two examples, both having the same issue. Thanks a lot for your support!

Maybe a helpful information - the libtins part of my application consist of packet injection into an existing PCAP file. Therefore I have to compare the timestamp of the provided PCAP with the one of the packets to be injected. Assuming that I realize your suggestion and compare the original packet's size with the serialized packet's size, is it possible to serialize the packet (to get the timestamp) and then write the "raw" packet (to preserve all its information) to a file?

[1] https://www.dropbox.com/sh/ajzio82mh2cndzj/AACgfc27oMsOuPJJk82aY5_0a?dl=0

**Comment by mfontanini** [comment]
Oh, sorry, I completely forgot about this. I'll try to have a look at it tonight!

**Comment by patrickj0607** [comment]
Thank you! I am looking forward for your feedback as I am really struggling with this issue and I could not find any solution yet. 
Is it possible to write these Raw PDUs to a file (like a 1:1 copy)? I saw that the `PacketWriter` requires a PDU or Packet, so it cannot be used to write Raw PDUs I suggest.

**Comment by mfontanini** [comment]
I tested this only with the "example 1" file you provided. I used some code like yours to copy the files from the input pcap file into an output one. I can confirm that both files now differ in size:

```
-rw-r--r-- 1 matias matias 3.3M Sep 11 10:22 /tmp/input_44CON-gsm-uplink-downlink-sim-example.pcap
-rw-r--r-- 1 matias matias 2.4M Sep 11 10:22 /tmp/output.pcap
```

Now, I wrote another code to go through both files at once, serializing and comparing the packets:

```c++
#include <tins/tins.h>
#include <iostream>

using namespace Tins;
using namespace std;

int main(int argc, char* argv[]) {
    if (argc != 3) {
        cout << "Missing input/output files\n";
        return 1;
    }

    FileSniffer sniffer1(argv[1]);
    FileSniffer sniffer2(argv[2]);
    Packet p1 = sniffer1.next_packet();
    Packet p2 = sniffer2.next_packet();
    while (p1 && p2) {
        auto b1 = p1.pdu()->serialize();
        auto b2 = p2.pdu()->serialize();
        if (b1 != b2) {
            cout << "Found different packets!\n";
        }
        p1 = sniffer1.next_packet();
        p2 = sniffer2.next_packet();
    }
    if (!!p1 != !!p2) {
        cout << "Found different amount of packets in files!\n";
    }
}
```

This code will output something if the files contain different amount of files or if the packets on both files on any given position differ on size. This code works fine and doesn't print anything if run with both files. This means packets are not being altered.

Now, if you run a `file` on the files, you'll see this:

```bash
$ file /tmp/input_44CON-gsm-uplink-downlink-sim-example.pcap /tmp/output.pcap
/tmp/input_44CON-gsm-uplink-downlink-sim-example.pcap: pcap-ng capture file - version 1.0
/tmp/output.pcap:                                      tcpdump capture file (little-endian) - version 2.4 (Ethernet, capture length 65535)
```

libtins will write output files using the pcap format, while the one you provided is written using pcap-ng, which is a newer format that contains some extra stuff. The smaller size you are seeing is just this extra overhead not being present on the libtins output file because of the different format being used.

I re-ran the initial code to copy the packets from one file onto another using the initial output file as the input and can confirm the sizes are the same, which makes sense because the input file is already using the smaller, pcap, format.

**Comment by patrickj0607** [comment]
Hi Mathias, sorry for the inconvenience! Because of the same file extensions I did not note the different file format. As I obtained the files from public datasources, I did not know that PCAP-NG was used. Thank you so much for your support.

Best regards,
Patrick
