### ISSUE TITLE
non blocking support in libtins

### ISSUE THREAD

**Issue by motazreda** [mfontanini/libtins#165]
guys need to know if i recieved a many many packets and i process every one of it on the fly is that cause lose of packets or libtins use nonblocking to handle that

for example
i get packet and process it with some code, while process packet 1, is this may cause to loose packet 2 and 3 because i'm not finished processing packet 1

thanks

**Comment by mfontanini** [comment]
Normally you want to implement some queuing so you have a sniffing thread that pushes packets as fast as it can into a queue and then have a consumer thread that actually processes them. There's no implementation of this in the library because:

* You literally just need a queue.
* The type of queue you need depends on what you want to do. If you don't process packets fast enough, you might want to drop the newer packets, or implement a ring buffer and drop the old ones, etc.

**Comment by motazreda** [comment]
you mean that make thread for adding packets in queue and other thread for reading from it ?

**Comment by mfontanini** [comment]
Yes, exactly that.

**Comment by motazreda** [comment]
oh thanks bud :)
