### ISSUE TITLE
Need Loopback PDU Usage and Behavior Explanation

### ISSUE THREAD

**Issue by solvingj** [mfontanini/libtins#236]
We're trying to create an effective and conventient way to test our libtins-based solution.  Our current challenges is how to create effective integration tests where we can launch real network client & server apps on the local machine, connect the two, and then capture the conversation.  Also, we want to try to do so in a portable way, starting with windows 10.  Our first look was at generating traffic to/from our own ethernet adapter, but we found we could not see that when capturing on the ethernet adapter.  Then we found we could see it when capturing on the loopback adapter, but this seems to have different behaviors and caveats compared to capturing real traffic.  We were immediately perplexed by the "Loopback PDU"... first how to use it, and second whether it's an acceptible way to do our testing.  On a side note, Loopback PDU seems like it could warrant an FAQ document.  We're hopeful that some sort of simple cast or method calls can get us an IP PDU out of the Loopback PDU, but we haven't found that yet.  We really don't want to have to involve virtual machines, which is what we're doing now as a workaround. 

Thanks in advance.

**Comment by mfontanini** [comment]
Could you be more specific? I don't understand your question regarding "how to use" the loopback PDU. This PDU is used by BSD (check http://www.tcpdump.org/linktypes.html, `DLT_NULL` is the constant that would be used) so I'm not sure if you'll see it on Windows. I don't think you're supposed to send Looopback PDUs, it's just a way for the kernel to wrap the captured packets when using a loopback interface. I think Windows just uses fake Ethernet headers.

Besides that, the `Loopback` PDU is just like any other, you don't need to do anything strange to find an IP PDU if you have a Loopback one, just call `find_pdu` and that would find it.

**Comment by solvingj** [comment]
We're seeing it on windows when we capture from the npcap loopback adapter (presumably because it's a port).  We're not trying to send using the loopback, but capture from it, and only because capturing from our wifi adapters did not show the packets from "self.ip" to "self.ip".  When we captured on the loopback, we saw lots of Loopback packets.  They were obviously the packets we wanted as we saw the same packets in wireshark, but in wireshark they were regular IP packets.  We tried casting and calling inner_pdu on the Loopback packets, but it did not give us an IP PDU.

**Comment by solvingj** [comment]
Again to clarify, we would prefer to just capture from our physical adapter if there's a setting we can set to be able to see our traffic.

**Comment by klemens-morgenstern** [comment]
So EthernetII should be replaced by Loopback, while the inner PDUs are the same? Well then it seems it's a bug, because that's not the behaviour I see. Fyi: I'm using the npcap loopback on windows and I guess that could be a missing feature or bug in libtins. Do you have any pointers where I might look?

**Comment by mfontanini** [comment]
Can you provide a packet capture? It's hard to estimate what could be happening without seeing any actual data. Note that you can check what's the next layer after a Loopback by checking the inner PDU's `pdu_type`, so you don't have to guess what's next.

**Comment by klemens-morgenstern** [comment]
I don't think I can; I just sent a TCP Request to 127.0.0.1 (or my own IP on 192.168.0.*) and got a bunch of Loopbacks with no inner pdu. Not much to share there really.

**Comment by klemens-morgenstern** [comment]
Oh btw. npcap works as a drop-in replacement for WinPCap quite seamlessly and I have the same behaviour with both, while wireshark gets the data.

**Comment by mfontanini** [comment]
"With no inner PDU" < that helps already. Can you call `Loopback::family` on them and post the value here?

**Comment by mfontanini** [comment]
Ah wait, that makes sense. `Loopback` isn't trying to construct any inner PDU on Windows (check loopback.cpp). If you remove the `#ifdef _WIN32` in there, does it work? I added that because at some point that wouldn't compile on Windows but maybe it does on more recent versions? (or I missed some include)

**Comment by klemens-morgenstern** [comment]
Sure thing, 2. Thanks for looking into it so fast!

**Comment by solvingj** [comment]
@mfontanini just to clarify, there's no way to capture packets that are sourced from our physical network adapter IP and destined to that same physical adapter IP, correct?  The operating system "shortcuts" that somehow so that it never hits the physical interface?

**Comment by klemens-morgenstern** [comment]
@mfontanini You sir, are awesome. That was it, worked by removing the latter two, i.e. all except the includes.. Should I create a PR or will you add a hotfix?

**Comment by mfontanini** [comment]
I'm fixing it now, also adding IPv6 in there. I added that guard while making it build on Windows for the first time, so I imagine there was a reason for that to be there. Now, I don't know what happened as I'm currently being able to build it just fine...

**Comment by klemens-morgenstern** [comment]
My guess is that you assumed you just cannot use the loopback because you were unaware of the npcap loopback adapter (as was I about three days ago) ;).

**Comment by mfontanini** [comment]
See, that's the thing. It was introduced in a [commit](https://github.com/mfontanini/libtins/commit/73577c744a6aa9c9582c77500d171db37acbd9d9#diff-ccc0ca2c0aa1f9a5aa3a4f80decc4713R61) where I was just making the library *build* on Windows, I wasn't testing it. This has nothing to do with the capture driver as this is currently building just with WinPCAP. 

Anyway, the fix is on branch `develop` now. If it builds properly on appveyor/travis, I'll merge it to master right away.

@solvingj yeah. packets you send to yourself will be routed to the loopback adapter.

**Comment by solvingj** [comment]
@mfontanini so is it actually impossible to capture Windows 10 Loopback traffic with the WinPCap SDK?  I know there are two NDIS6 implementations (NPCap and Win10PCap) to get around limitations of the old WinPCap NDIS5 model, but I didn't see this listed as one of them (which would be a surprise).

**Comment by mfontanini** [comment]
I don't normally use Windows so I'm not sure of what you can/can't do.

If you just need to capture traffic, can't you just use pcap files and use `FileSniffer` only for testing purposes? At work we were implementing some traffic analysis tool and that was our way to perform integration tests.

**Comment by solvingj** [comment]
I don't know, that's why I like starting conversations so much... I didn't even think of that as an option, will certainly explore.  Thanks again!

**Comment by mfontanini** [comment]
So, just for the record, the reason that `#ifdef` was added is because Windows doesn't have `PF_LLC`. Later, I added [this](https://github.com/mfontanini/libtins/blob/master/src/loopback.cpp#L49) workaround for BSD which also doesn't have that macro, so this actually fixed both the BSD and Windows builds, but the latter already had this "workaround" (e.g. not doing anything on `Loopback`).

**Comment by solvingj** [comment]
I think we're set on our loopback manipulation at this time, thanks again for the amazing response!
