### ISSUE TITLE
Constructing and Sending ARP Response with Custom MAC

### ISSUE THREAD

**Issue by solvingj** [mfontanini/libtins#238]
We are able to send ICMP requests with a custom MAC addresses, and remote hosts receive them. 

However, we when we try to send ARP responses (in response to a ARP requests) with a custom MAC address, the remote hosts do not receive them.

We have tried several variations on constructing senders and the ARP PDU's, but there are obviously many ways to do this and nuances depending on the PDU type.  

Can someone show an example of how we might properly construct an ARP response with a custom MAC?

**Comment by mfontanini** [comment]
Sending ARP responses is pretty straightforward, there's not too many fields you can play around with. Are you using Windows? Are you using the pcap interface to send packets? e.g. `USE_PCAP_SENDPACKET_DEFAULT` on CMake (this is enabled by default). Otherwise I think Windows may block some types of packets, possibly including ARP responses, especially if you're trying to do ARP poisoning. 

Can you see the packet going out from your host but not being received at all by the other? Is there some device in between that could be dropping it?

**Comment by klemens-morgenstern** [comment]
We're using the default cmake-setup (with `PacketSender`) and npcap, but I'll try the `USE_PCAP_SENDPACKET_DEFAULT` option. 
The packet is visible for wireshark on the same machine, but never reaches the other one (i.e. the one sending the request).

**Comment by solvingj** [comment]
Yes windows, no nothing that could block it.  Looking forward to results from USE_PCAP_SENDPACKET_DEFAULT.

**Comment by mfontanini** [comment]
How are you constructing the ARP response? Which host's MAC address are you using on the ethernet layer?

**Comment by klemens-morgenstern** [comment]
I'M constructing with `make_arp_reply` and use the Custom MAC on both layers. I enabled `USE_PCAP_SENDPACKET_DEFAULT` but that doesn't change a thing.

**Comment by mfontanini** [comment]
Just seeing this, I wrote that function years ago, but that will only work if there's no device in between you and the target. Otherwise you need to use whatever device is in the middle's MAC address as the target on the ethernet layer. e.g.

```[you] <-> [router] <-> [target]```

If you send the packet and the target MAC (ethernet layer) is `target`, then `target` won't receive it as it has to go through the router first and the router will drop any packets that don't target it (targeting meaning that the ethernet target MAC is its address).

Hence in this case you have to do whatever `make_arp_reply` is doing but as the target MAC address in the ethernet layer you have to use whatever router there is in between you and the target host.

**Comment by solvingj** [comment]
Just as a refresher for clarity, ARP does not go through routers.  ARP is done via layer 2 broadcast on a layer 2 segment.  We're testing with 2 peers connected via ethernet switch.  There is a router on the subnet, but it's presence is irrelevant.

**Comment by mfontanini** [comment]
ARP requests are done using the broadcast address but responses target specific hosts. Even if you're using a switch, the switch has a MAC address so if you send a packet with an address that's not the switch's then it should be dropped by it.

**Comment by solvingj** [comment]
The switch does not have a mac address.  The mac address does not do any layer 2 filtering, it only builds a MAC address table of which MAC's it's seen from which ports.  

To be clear, "smart switches" (any switch which holds an IP for administration) do have mac addresses, however this is a dumb layer 2 switch.  I can get out a hub I used for packet captures in the past to prove beyond reasonable doubt that the packet is not hitting the network at all, but I'm quite certain it's not.  Furthermore, if we can't get the packet across a dumb layer 2 switch, then we it won't work for us anyway.

**Comment by mfontanini** [comment]
Well, it's simple. Run something that makes your target send an ARP request asking for your source's MAC. That will trigger your source to send a valid ARP response. Capture it, making sure it actually works. Then build the same packet in your app and send it.

**Comment by solvingj** [comment]
It looks like it may be npcap related.  We recompiled to winpcap and now the replies are coming to the other host successfully.  Will start looking into sources for clues.

**Comment by mfontanini** [comment]
Any updates on this one?

**Comment by solvingj** [comment]
No, ok to close, don't even think it's still an issue .
