### ISSUE TITLE
Adding multiple IPv6 extension headers

### ISSUE THREAD

**Issue by laudrup** [mfontanini/libtins#268]
I am currently using your excellent library to write some unittests for some packet parsing code.

In doing that, I wanted to make sure that multiple IPv6 extension headers are parsed correctly, but it doesn't seem like there's any simple way to add more extension headers.

If I'm reading the code and documentation correctly, it seems like the `next_header()` function can be used to set that value for the IPv6 header and `add_header()` can be used to add additional headers, but they do not touch the previous extended headers next_header field.

I would find it most logical if the `next_header()` function was removed and extension headers could be added by simply calling `add_header()` for each extension header to be added, which would then update the next_header field of the previous header. It seems like this currently has to be done by crafting the header fields manually and setting the next_header field manually.

Am I missing something?

You library is very easy to use and well designed so I assumed that was how it would work by looking at the documentation.

I will be happy to try and implement that functionality and send you a pull request if that's any help, but again, it is very likely that I have misunderstood something.

Thanks a lot.

**Comment by mfontanini** [comment]
Hey there,

recently I changed the way IPv6 extension headers are handled, you can use the latest code in master (what will eventually be libtins v4.0). Before that, the extensions were not properly handled, meaning there was no simple way to iterate and see which headers were there as the headers basically contained the values in the parsed packet "as is", meaning if you grabbed a header and asked it for it's `option` value (type of option), it would return the next option's type, which as much as it mimics how that's actually defined under the hood, it's not ideal when iterating. 

After that change, it works in a different (which I think is better) way:
* Extension headers always contain their own type. If you add an extension header of type X, the `option` function will actually return type X even after you've pushed it into the IPv6 object.
* When the IPv6 PDU is serialized, all "next header" values are corrected on the serialized payload. This means that, while the headers contained their own type when stored inside the IPv6 PDU, when they're serialized, they will actually contain the next header's value. You can check this portion of the code [here](https://github.com/mfontanini/libtins/blob/master/src/ipv6.cpp#L255).
* After serializing, the internal option types are reverted back so that again each option contains its own type and not the next header's one. Code [here](https://github.com/mfontanini/libtins/blob/master/src/ipv6.cpp#L287).

So `add_header` should add a header with the provided type at the end of the header list. The previously last header's next header type will be updated but only during serialization. This should work properly as I added [some tests](https://github.com/mfontanini/libtins/blob/master/tests/src/ipv6_test.cpp#L344) for it but if you find some case where it isn't, please let me know.

Regarding `next_header`, it's just a way of overriding the next protocol type but that will only work if there's no extension headers being added and the next PDU after IPv6 is of an [unknown type](https://github.com/mfontanini/libtins/blob/master/src/ipv6.cpp#L269). It's mostly useless but I guess someone could find a use for it. The documentation should probably say that it will be overridden if there's at least one extension header in the PDU though.

**Comment by laudrup** [comment]
Hi again,

Thanks a lot for your long and detailed answer.

I am currently using the 3.5 release, not the master branch, I forgot to mention that. Sorry about that.

It sounds like the implementation you have made on the master branch is exactly what I was looking for. Thanks a lot for this.

I will prefer to wait for the 4.0 release then, but if it will be any help for you, I will be happy to test my code against the current master if you want.

Thanks once again for creating this great library. It has been really helpful for me.
