### ISSUE TITLE
Dot11 Docs

### ISSUE THREAD

**Issue by MisterBianco** [mfontanini/libtins#294]
I seem to be unable to find the Dot11 docs? Have they been moved/removed? If so why and how can I get them back? O.o

**Comment by MisterBianco** [comment]
Seriously am I crazy or are there no Dot11 docs?

**Comment by mfontanini** [comment]
Looks like the Doxyfile should have `LIBTINS_ENABLE_DOT11` inside [PREDEFINED](https://github.com/mfontanini/libtins/blob/master/docs/Doxyfile.in#L1368). You can add that locally and run `make docs` inside the build directory (you need to have doxygen installed for this) for now until it's fixed in the website.

**Comment by MisterBianco** [comment]
OK just making sure I wasn't stupid. I will have to do just that. Thanks sir
