### ISSUE TITLE
TCPStreamFollower Error!

### ISSUE THREAD

**Issue by goesang** [mfontanini/libtins#53]
My code is this
 
    bool print(TCPStream &www){
	const RawPDU::payload_type& payload = www.server_payload();
	std::cout<<payload.size()<<std::endl;
	return true;
    }

    int main() {
	Sniffer eth("eth0");
	TCPStreamFollower test = TCPStreamFollower();
	test.follow_streams(eth,print);
	return 1;
    }
And captured the Ubuntu downloading. (http://releases.ubuntu.com/12.04/ubuntu-12.04.4-desktop-i386.iso)

Ubuntu size is more than 700mb. But stop at 20mb. 

What is the problem?

**Comment by mfontanini** [comment]
Without having a pcap to reproduce the problem it is very hard to say what's happening. Please attach one.

In the meantime, this could be caused by your application being dropping packets. You should be consuming the payload, not letting it grow until the entire stream is seen. Every few packets, you'll have some big reallocations otherwise, and this will affect performance for sure, especially if you're parsing a 700MB stream.

**Comment by goesang** [comment]
Thank you for answers.
I am still a beginner developer.
(English is not good.)
What I want to do a tcp real-time analytics on large computers.
Like wireshark follow TCP stream ...
Is there any other way to libtins?
