### ISSUE TITLE
ids or ips product 

### ISSUE THREAD

**Issue by jiamo** [mfontanini/libtins#88]
Like bro snort suricata. Do you have plan make libtins a good replace of libpcap for developers who want build a ips product on libtins?

**Comment by mfontanini** [comment]
libtins is not meant to be a replacement for libpcap. libpcap allows capturing packets, while libtins allows parsing them and crafting them.

I don't understand the question. What should be changed to allow this? (besides increasing the performance, which I'm working on).

**Comment by jiamo** [comment]
something like make tcp stream followed on the fly and give the tcp payload to a next layer(http layer writed by customer developer). the main process is capturing pcap and maintain hash tables (for every tcp session don't finish) When a pkt coming, it can be followed its own session,  a callback func can be called if the seq is right order.

**Comment by jiamo** [comment]
may be some functions like in https://github.com/sch3m4/libntoh

**Comment by mfontanini** [comment]
Although this would be a really interesting thing, I think it might be something to implement on a different library. In order to make something like that which works correctly you'd need to use a bunch of threads to parse packets, reassemble them, etc. It's a pretty big thing.

On the other hand, I think the TCPStreamFollower class could be modified so it offers a much better view into what's happening with each stream it's reassembling. I don't really like how that class works right now.

**Comment by mfontanini** [comment]
Closing this as it's out of the scope of this project.
