### ISSUE TITLE
Parallel Read of pcap files (Linux)

### ISSUE THREAD

**Issue by kaatish** [mfontanini/libtins#92]
Is it possible to load a pcap file in memory on linux and have multiple threads read it in parallel? How can that be achieved? As far as I can understand, sniff_loop() and next_packet() are inherently sequential in nature.

**Comment by mfontanini** [comment]
That can't be done using libtins directly and I don't think it can be done using libpcap either. The pcap format is sequential (there's always a header before each packet), so you can't just "jump to packet X". 

I guess you could write your own pcap parser which would mmap the file, see the sizes in packet headers and jump through the offsets as to identify where each packet begins, and then perform the actual parsing in parallel. Although I really don't think this is going to be faster, since you'll end up requiring the entire file to be in memory in order to scan through it.
